### ISSUE TITLE
crash with fast-forwarded high score playback

### ISSUE THREAD

**Issue by pphaneuf** [quadra-game/quadra#35]

**Comment by pphaneuf** [comment]
Submitted by Brant Gurganus (brantgurga):

I receive a crash when I fast-forward through high
score recordings.

Procedure:
1. Start quadra.
2. Show high scores.
3. Download high scores if necessary.
4. Start playback.
5. Hold the fast forward button down.

Expected results:
Recorded high scoring games are played back flawlessly.

Actual results:
Quadra experiences a segmentation fault.

Details:
I obtained a stack dump of:
#0 Sound::process() (this=0x8323090) at
skelton/svgalib/sound.cpp:196
#1 0x080c803b in start_frame () at
skelton/svgalib/main.cpp:57
#2 0x080aadd7 in start_game () at source/quadra.cpp:2404
#3 0x080c8122 in main (ARGC=2, ARGV=0xbffff334,
ENV=0xbffff340)
at skelton/svgalib/main.cpp:105

Quadra was compiled without stripping executables on
gentoo using the following CFLAGS (assuming the ebuild
does not strip any or add any of its own):
-O3 -march=pentium4 -mcpu=pentium4
-maccumulate-outgoing-args -fprefetch-loop-arrays
-ftracer -pipe -g

I receive the same stack dump if I compile only with -g3:
#0 0x080f9db3 in Sound::process() (this=0x835c090)
at skelton/svgalib/sound.cpp:195
#1 0x080f7be0 in start_frame() () at
skelton/svgalib/main.cpp:57
#2 0x080cd3f4 in start_game() () at source/quadra.cpp:2404
#3 0x080f7d6c in main (ARGC=1, ARGV=0xbffff344,
ENV=0xbffff34c)
at skelton/svgalib/main.cpp:105

As the stack dumps occur while processing sound, it
would seem that quadra is in some way playing too many
sounds at the same time or something along those lines.

I would have tried recreating the issue by disabling
sound, but I could not find a place in Quadra or from
command line to disable sound.

**Comment by pphaneuf** [comment]
appleman1234 says that this is fixed in Subversion, which I'm inclined to believe,
with the reference counting of Samples in Playing_sfx dgryski added.
